# Numpy

In [1]:
import numpy as np

In [2]:
L1 = [1,2,3,4,5,6,7]

In [3]:
L1

[1, 2, 3, 4, 5, 6, 7]

In [4]:
x = np.array(L1)
x

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
x2 = np.array(L1, dtype='float32')
x2

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,12, dtype=np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [11]:
np.arange(4,5, 0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [97]:
np.linspace(1., 7., 50)

array([1.        , 1.12244898, 1.24489796, 1.36734694, 1.48979592,
       1.6122449 , 1.73469388, 1.85714286, 1.97959184, 2.10204082,
       2.2244898 , 2.34693878, 2.46938776, 2.59183673, 2.71428571,
       2.83673469, 2.95918367, 3.08163265, 3.20408163, 3.32653061,
       3.44897959, 3.57142857, 3.69387755, 3.81632653, 3.93877551,
       4.06122449, 4.18367347, 4.30612245, 4.42857143, 4.55102041,
       4.67346939, 4.79591837, 4.91836735, 5.04081633, 5.16326531,
       5.28571429, 5.40816327, 5.53061224, 5.65306122, 5.7755102 ,
       5.89795918, 6.02040816, 6.14285714, 6.26530612, 6.3877551 ,
       6.51020408, 6.63265306, 6.75510204, 6.87755102, 7.        ])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [101]:
x= np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [103]:
x.reshape((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
x2 = np.array([[1,2,3,4],[5,6,7,8]])
x2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.ravel(x2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
x3.flatten(x2)

NameError: name 'x3' is not defined

In [19]:
x2.flatten(x2)

ValueError: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead

In [20]:
x2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.transpose(x2)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
np.resize(x2, (5,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

# Propiedades Numpy

In [24]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
x.ndim

2

In [28]:
x.shape

(3, 4)

In [29]:
x.size

12

In [30]:
x.dtype

dtype('int32')

In [31]:
x.itemsize

4

In [32]:
x.data

In [33]:
x[2]

array([ 8,  9, 10, 11])

In [34]:
x[2,1]

9

In [35]:
x.shape = (4,3)

In [36]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [38]:
y= np.arange(12)
y[2:6]

array([2, 3, 4, 5])

In [39]:
y[1:7:2]

array([1, 3, 5])

In [40]:
z = np.arange(10,6, -1)
z

array([10,  9,  8,  7])

In [41]:
m = np.arange(50)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [42]:
m[m>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [43]:
cond = (m<25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [44]:
m[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
m[12:24]=1
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [46]:
m[13:16]=[6,9,12]
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
m[5]=3.1415
m

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Potencial Numpy

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
x-4

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [51]:
x/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [52]:
x*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [53]:
alpha = np.linspace(0,2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [54]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [55]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [56]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [57]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [58]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [59]:
np.power(3, x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [60]:
np.exp(x,2)

TypeError: return arrays must be of ArrayType

In [61]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [62]:
np.sum(x)

45

In [63]:
np.nansum(x)

45

In [64]:
np.prod(x)

0

In [65]:
np.mean(x)

4.5

In [66]:
np.median(x)

4.5

In [67]:
np.min(x)

0

In [68]:
np.max(x)

9

In [69]:
np.std(x)

2.8722813232690143

In [70]:
np.var(x)

8.25

In [71]:
np.percentile(x, 9=0.5)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (<ipython-input-71-3b96ccf11996>, line 1)

In [73]:
np.percentile(x, 0.5)

0.045

In [74]:
np.any(x)

True

In [104]:
np.random.seed(2010)
z = np.random.random((3,10))
z

array([[0.04245198, 0.40503665, 0.48763384, 0.93669396, 0.48820644,
        0.38623613, 0.23353075, 0.78961931, 0.3696408 , 0.00220124],
       [0.4189598 , 0.31413043, 0.37338473, 0.44975969, 0.58257541,
        0.67417719, 0.87708282, 0.97809998, 0.83188633, 0.52109033],
       [0.68988251, 0.1791633 , 0.19472995, 0.74259996, 0.19508389,
        0.00504909, 0.65296971, 0.43364929, 0.94960884, 0.81861492]])

In [93]:
z.sum()

6.280061166023237

In [94]:
z.sum(axis=0)

array([0.8476479 , 0.95269784, 1.65063788, 1.75609446, 1.07298309])

In [95]:
z.sum(axis=1)

array([2.36002288, 1.78122823, 2.13881006])